const LOGIN = "LOGIN_HERE";
const PASSWORD = "PASSWORD_HERE";
const RESPOND_TO_MENTIONS = 1;
const RESPOND_TO_COMMANDS = 1;
const RESPOND_TO_PRIVATEMESSAGES = 0;

const RATSIGNAL_CONTACT_ROLES = [
];

const RATSIGNAL_EMERGENCY_CHANNEL = "";

const TRILATERATION_CONTACT_ROLES = [
];

const TRILATERATION_CONTACT_EDSMUSERS = 1;
const EDSM_ENABLE_SUBMISSION = 0;

const EDSM_SUBMIT_ROLES = [
	"admin"
];

const EDSM_USE_BETASERVER = 0;
const EDMATERIALIZER_USE_BETASERVER = 0;

const USE_TRELLO = false;
const TRELLO_KEY = 'TRELLO_KEY';
const TRELLO_TOKEN = 'TRELLO_TOKEN';
const TRELLO_BOARDS = [
	{
		id:'BOARD_ID',
		channel:'#operations'
	},
	{
		id:'BOARD_ID',
		channel:'#operations'
	}
];

module.exports.LOGIN = LOGIN;
module.exports.PASSWORD = PASSWORD;
module.exports.RESPOND_TO_MENTIONS = RESPOND_TO_MENTIONS;
module.exports.RESPOND_TO_COMMANDS = RESPOND_TO_COMMANDS;
module.exports.RESPOND_TO_PRIVATEMESSAGES = RESPOND_TO_PRIVATEMESSAGES;
module.exports.RATSIGNAL_CONTACT_ROLES = RATSIGNAL_CONTACT_ROLES;
module.exports.RATSIGNAL_EMERGENCY_CHANNEL = RATSIGNAL_EMERGENCY_CHANNEL;
module.exports.TRILATERATION_CONTACT_ROLES = TRILATERATION_CONTACT_ROLES;
module.exports.TRILATERATION_CONTACT_EDSMUSERS = TRILATERATION_CONTACT_EDSMUSERS;
module.exports.EDSM_ENABLE_SUBMISSION = EDSM_ENABLE_SUBMISSION;
module.exports.EDSM_SUBMIT_ROLES = EDSM_SUBMIT_ROLES;
module.exports.EDSM_USE_BETASERVER = EDSM_USE_BETASERVER;
module.exports.EDMATERIALIZER_USE_BETASERVER = EDMATERIALIZER_USE_BETASERVER;

module.exports.USE_TRELLO = USE_TRELLO;
module.exports.TRELLO_KEY = TRELLO_KEY;
module.exports.TRELLO_TOKEN = TRELLO_TOKEN;
module.exports.TRELLO_BOARDS = TRELLO_BOARDS;
